name: 发布Python包到PyPI

on:
  release:
    types: [created]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: 构建并发布
      env:
        TWINE_USERNAME: __token__  # 使用固定值 __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # 使用API令牌
      run: |
        python -m build
        twine upload dist/*
